### ISSUE TITLE
Incorrect type: expected "object" - YAML

### ISSUE THREAD

**Issue by JamieP83** [joshjcarrier/homeassistant-litter-robot#42]
Hey all,
love this integration, thanks a lot for creating it! (will you add it to the main Home Assistant so its out the box?)

Home Assistant 2021.1.5

I copied the core YAML but I get an error, for the 2 times where it says "turn_off"

![image](https://user-images.githubusercontent.com/48566948/106257067-fc327d00-6213-11eb-96e4-433af5379021.png)

```
  - platform: template
    switches:
      litter_robot_nightlight:
        friendly_name: "Shitron"
        value_template: " {{ is_state('sensor.litter_robot_shitron_nightlight', 'On') }}"
        icon_template: "mdi:lightbulb"
        turn_on:
          service: litter_robot.nightlight_turn_on
        turn_off:
          service: litter_robot.nightlight_turn_off
      litter_robot_cycle:
        friendly_name: "Shitron Cycle"
        value_template: " {{ is_state('sensor.litter_robot_shitron_status', 'Clean Cycling') }}"
        icon_template: "mdi:refresh"
        turn_on:
          service: litter_robot.cycle
        turn_off:
      litter_robot_reset_drawer:
        friendly_name: "Shitron Reset Drawer"
        value_template: " {{ is_state('sensor.litter_robot_shitron_status', 'Clean Cycling') }}"
        icon_template: "mdi:repeat"
        turn_on:
          service: litter_robot.reset_drawer
        turn_off:
```
