### ISSUE TITLE
Litter robot Last seen date in HA does not match the Whisker app

### ISSUE THREAD

**Issue by Waank1** [joshjcarrier/homeassistant-litter-robot#50]
When my cat uses the robot, the Last Seen sensor automatically updates on the Whisker app,  The one from the api in Home Assistant is always wrong.  Wondering if anyone else has had the same problem and is there a 'fix'?

**Comment by axolotls666** [comment]
> When my cat uses the robot, the Last Seen sensor automatically updates on the Whisker app, The one from the api in Home Assistant is always wrong. Wondering if anyone else has had the same problem and is there a 'fix'?

Last Seen doesn't work in my HA. I use the "Status Code" entity and when it changes to "Cat Sensor Timing" that matches the app time.

**Comment by Waank1** [comment]
Thanks [axolotls666], I'm not really sure how to do that, do you make a template sensor?

**Comment by axolotls666** [comment]
> Thanks [axolotls666], I'm not really sure how to do that, do you make a template sensor?

No. Just look for the state. "cst" means the cat is in getting in the litter robot (or at least touching it).

trigger:
  - platform: state
    entity_id:
      - sensor.{name of your litter robot}_status_code
    to: cst

then add your condition and/or action after. This is in my automation.

**Comment by Waank1** [comment]
Thanks!  using cst I was able to write the following:
Now the new sensor Cat Poop Time matches that in the Whisker app.

```
  - trigger:
      - platform: state
        entity_id: sensor.kitty_shitty_status_code
        to: 'cst'
    sensor:
      - name: Cat Poop Time
        state: "{{ now().timestamp() | timestamp_custom('%A, %B %d at %H%M') }} "  
```
